services:
  phpfpm:
    # At the time of writing, dpl-cms requires PHP 8.3 (!) (cf.
    # https://github.com/danskernesdigitalebibliotek/dpl-cms/blob/develop/composer.json#L102)
    image: itkdev/php8.3-fpm:latest
