#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
project_dir=$(cd "$(dirname "$script_dir")" && pwd)

cd "$project_dir" || exit

compose() {
  docker compose "$@"
}

composer() {
  compose exec dpl-cms composer "$@"
}

drush() {
  compose exec dpl-cms vendor/bin/drush "$@"
}

shell() {
  compose exec dpl-cms "$@"
}

set -x

drupal_dir=dpl-cms
# Extract the module path from the service.
module_path=$(compose run --rm dpl-cms sh -c 'echo $MODULE_PATH')

compose down --remove-orphans
compose pull
# mkdir -p dpl-cms/web/sites/default/files/modules_local
compose up --detach --remove-orphans --wait

shell curl --location --remote-name https://github.com/danskernesdigitalebibliotek/dpl-cms/archive/refs/heads/main.tar.gz
# https://linux.die.net/man/1/tar#content
shell tar xvf main.tar.gz --strip-components=1

composer config --no-plugins allow-plugins true
composer config extra.merge-plugin.include "$module_path/composer.json"
composer require drush/drush wikimedia/composer-merge-plugin

composer require --dev symfony/phpunit-bridge

# # Run PHPStan
# (cd "$drupal_dir/$module_path" && "$script_dir/$drupal_dir/vendor/bin/phpstan" --configuration=phpstan.neon.dist -vvv --debug)

# # Reset Drupal installation
# compose exec drupal sh -c 'find . -name .ht.sqlite -ls -delete; rm web/sites/default/settings.php' || true
# drush site:install --db-url='sqlite://sites/default/files/.ht.sqlite?module=sqlite' --yes
# drush pm:install azure_ad_delta_sync
# compose exec drupal php web/core/scripts/generate-proxy-class.php 'Drupal\azure_ad_delta_sync\UserManager' "$module_path/src"
# compose exec drupal php web/core/scripts/generate-proxy-class.php 'Drupal\azure_ad_delta_sync\Controller' "$module_path/src"
# compose down --remove-orphans


# ------------------------------------------------------------------------------


# #!/usr/bin/env bash

# script_dir=$PWD
# module_name=dpl_pretix
# drupal_dir=vendor/drupal-module-code-analysis
# # Relative to $drupal_dir
# module_path=web/sites/default/files/modules_local/$module_name

# cd "$script_dir" || exit

# drupal_composer() {
#   composer --working-dir="$drupal_dir" --no-interaction "$@"
# }

# set -x

# rm -fr "$drupal_dir"
# git clone --branch=develop --depth=1 https://github.com/danskernesdigitalebibliotek/dpl-cms "$drupal_dir"

# # Copy our code into the modules folder
# mkdir -p "$drupal_dir/$module_path"

# # https://stackoverflow.com/a/15373763
# rsync --archive --delete --compress . --filter=':- .gitignore' --exclude "$drupal_dir" --exclude .git "$drupal_dir/$module_path"

# drupal_composer config minimum-stability dev

# # Allow ALL plugins
# # https://getcomposer.org/doc/06-config.md#allow-plugins
# drupal_composer config --no-plugins allow-plugins true

# drupal_composer require wikimedia/composer-merge-plugin
# drupal_composer config extra.merge-plugin.include "$module_path/composer.json"
# # https://www.drupal.org/project/drupal/issues/3220043#comment-14845434
# drupal_composer require --dev symfony/phpunit-bridge

# # Run PHPStan
# (cd "$drupal_dir/$module_path" && "$script_dir/$drupal_dir/vendor/bin/phpstan" --configuration=phpstan.neon.dist -vvv --debug)
