#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

cd "$script_dir" || exit

compose() {
  docker compose "$@"
}

composer() {
  compose exec dpl-cms composer "$@"
}

drush() {
  compose exec dpl-cms vendor/bin/drush "$@"
}

shell() {
  compose exec dpl-cms "$@"
}

compose up --detach --build

shell vendor/bin/phpstan --configuration=web/sites/default/files/modules_local/dpl_pretix/phpstan.neon.dist

compose down
