services:
  dpl-web:
    build:
      # context: .
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        # check=skip=SecretsUsedInArgOrEnv

        FROM itkdev/php8.4-fpm:latest
        ENV PHP_MEMORY_LIMIT=512M

        # https://stackoverflow.com/a/33439625
        SHELL ["/bin/bash", "-c"]

        WORKDIR /app

        RUN export ref_type=$$(if [ "${DPL_WEB_VERSION:?}" = "main" ]; then echo heads; else echo tags; fi) \
          && curl --fail --verbose \
            --location https://github.com/danskernesdigitalebibliotek/dpl-web/archive/refs/$${ref_type}/${DPL_WEB_VERSION:?}.tar.gz \
            --output main.tar.gz \
          && tar xvf main.tar.gz --strip-components=2 \
          && rm main.tar.gz \
          && composer install

    user: root
    volumes:
      # - ./settings.local.php:/app/web/sites/default/settings.local.php
      # Mount our code into the web/modules/contrib folder
      - ../:/app/web/sites/default/files/modules_local/dpl_pretix
    environment:
      # Let the module path, i.e. the mounted path, be known in the container
      MODULE_PATH: web/sites/default/files/modules_local/dpl_pretix

      PHP_MAX_EXECUTION_TIME: 60
      PHP_MEMORY_LIMIT: 512M
